// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUgeeyE7NrlwuZkn-kx0W3xuwBLFWSXR4',
    appId: '1:979951130600:web:453fb1b02bcd1f6cdcb65d',
    messagingSenderId: '979951130600',
    projectId: 'sujacreations-26069',
    authDomain: 'sujacreations-26069.firebaseapp.com',
    storageBucket: 'sujacreations-26069.firebasestorage.app',
    measurementId: 'G-BNVVCVQCG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2yXPzClnEK6BA4E2Ryb837H-XBc9MeQ',
    appId: '1:979951130600:android:92971e67feb95b5adcb65d',
    messagingSenderId: '979951130600',
    projectId: 'sujacreations-26069',
    storageBucket: 'sujacreations-26069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBou1JfvzmO5HddJl-OE7OKdbQXp74NdZs',
    appId: '1:979951130600:ios:d645d245bdbdd22adcb65d',
    messagingSenderId: '979951130600',
    projectId: 'sujacreations-26069',
    storageBucket: 'sujacreations-26069.firebasestorage.app',
    iosBundleId: 'com.example.sujacreations',
  );
}
